name: Update Source Data

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch latest source-data
        run: |
          # Clone the source-data repository
          git clone --depth=1 https://github.com/zengin-code/source-data.git /tmp/source-data
          
          # Remove old data directory
          rm -rf data
          
          # Copy only the data directory from source-data
          cp -r /tmp/source-data/data data
          
          # Clean up
          rm -rf /tmp/source-data
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet && git diff --cached --quiet && [ -z "$(git ls-files --others --exclude-standard)" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Set up Go
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-go@v6
        with:
          go-version: '1.21'
      
      - name: Run tests
        if: steps.changes.outputs.changed == 'true'
        run: go test -v ./...
      
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update bank and branch data'
          title: 'chore: update bank and branch data'
          body: |
            This PR updates the bank and branch data from zengin-code/source-data.
            
            Please review the changes and merge if everything looks good.
          branch: update-source-data
          delete-branch: true

