name: Update Source Data

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update submodule
        run: |
          git submodule update --remote --merge source-data
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Set up Go
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Run tests
        if: steps.changes.outputs.changed == 'true'
        run: go test -v ./...
      
      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update source-data'
          title: 'chore: update source-data'
          body: |
            This PR updates the source-data submodule to the latest version.
            
            Please review the changes and merge if everything looks good.
          branch: update-source-data
          delete-branch: true

